# -*- coding: utf-8 -*-
"""self_movies

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ScWlHW1Gen1D0YO5P8hxmlumDNSjEQyA
"""

from pandas import *
mydf=read_csv("/content/tmdb_5000_movies.csv")
mydf
mydf.columns
mydf.info()

mydf["status"].head(10)

mydf.isnull().sum()

new=mydf[(mydf["budget"]>=200000000) & (mydf["budget"]<=3500000000)]
l=["budget","title"]
new[l]

# Q.1). Display top 10 rows the dataset.
mydf.head(10)

# 2). Check last 10 Rows of the dataset :
mydf.tail(10)

# 3). Check datatype of each column :
mydf.dtypes

# 4). Check null values in the dataset :
mydf.isnull().sum()

# 5). How many Rows and columns all in dataset :
sh=mydf.shape
print('no. of rows =',+sh[0])
print(f"no. of columns ={sh[1]}")
print()
mydf.info()

